---
cremad:
  fps: 30
  division: [0.8, 0.1, 0.1]
  emo_label: ['NEU', 'HAP', 'SAD', 'SUR', 'FEA', 'DIS', 'ANG']
  bad_sample: {
    '1076_MTI_NEU_XX', '1076_MTI_SAD_XX', '1064_TIE_SAD_XX', '1064_IEO_DIS_MD', 
    '1004_DFA_FEA_XX','1047_IEO_SAD_LO','1047_IEO_FEA_LO'
    }
  # debug configs
  debug: 0
  debug_load_size: 16
  
biwi:
  fps: 25
  train_subjects: {'F1', 'F2', 'F3', 'F4', 'F5', 'M3', 'M4'}
  test_subjects: {'F6', 'F7', 'F8', 'M1', 'M2', 'M6'}
  bad_sample: {
    'F1_36','F1_39','F1_e20' ,'F3_e02','F3_e03','F4_27','F6_36', 'M1_e01', 'M1_e02', 'M1_e03','M1_e04','M1_e05','M1_e06','M1_e07','M1_e08','M1_e09','M1_e10','M1_e11','M1_e12', 'M1_e13', 'M1_e14','M1_e15','M1_e16','M1_e17','M1_e18','M1_e19','M1_e20', 'M2_20', 'M6_21','F1_e12','F6_e21','F6_e31','M2_31','M2_e04','M2_e08','M6_e02','M6_e18','M6_e27'
  }
  # debug configs
  debug: 0
  debug_load_size: 16

vocaset:
  fps: 60
  emo_only: true # only use emotional sentences in VOCASET
  train_subjects: {
    'FaceTalk_170728_03272_TA', 'FaceTalk_170904_00128_TA', 'FaceTalk_170725_00137_TA', 'FaceTalk_170915_00223_TA',
    'FaceTalk_170811_03274_TA', 'FaceTalk_170913_03279_TA' , 'FaceTalk_170904_03276_TA', 'FaceTalk_170912_03278_TA'
  }
  valid_subjects: {
    'FaceTalk_170811_03275_TA', 'FaceTalk_170908_03277_TA'
  }
  test_subjects: {'FaceTalk_170809_00138_TA', 'FaceTalk_170731_00024_TA'}
  min_sec: 1.0
  max_sec: 10.0
  # fitting configs
  fitting:
    shape:
      max_iter: 100
      lr: 1.0e-2
      stop_eps: 0.0
    shape_2:
      max_iter: 60
      lr: 2.0e-2
      stop_eps: 0.0
    shape_quick:
      max_iter: 300
      lr: 1.0e-3
      stop_eps: 0.0
    detail:
      max_iter: 300
      lr: 5.0e-3
      stop_eps: 0.0
    detail_quick:
      max_iter: 300
      lr: 5.0e-3
      stop_eps: 0.0
  # debug configs
  debug: 0
  debug_load_size: 16

lrs2:
  fps: 25
  min_sec: 1.0
  max_sec: 4.0
  max_train_size: 3000
  max_val_size: 500
  bad_sample: {}
  # debug configs
  debug: 0
  debug_load_size: 16

ensemble_dataset:
  datasets: ['cremad', 'vocaset', 'lrs2']


