---
paths:
  config: ./configs
  dataset:
    norm_dict: ./datasets/cache/norm_dict.pt
    cache: ./datasets/cache
    biwi: ./datasets/BIWI
    cremad: ./datasets/CREMA-D
    lrs2: ./datasets/LRS2
    ravdess: ./datasets/RAVDESS
    vocaset: ./datasets/VOCASET
  module_test: ./inference/module_test
  inference:
    input: ./inference/input
    output: ./inference/output
    cache: ./inference/cache
    baseline_test: ./inference/baseline_test
    visualize: ./inference/visualize
  log: ./logs
  figures: ./logs/figures
  model: ./models
  script: ./scripts
  fitting: ./fitting
  3rd:
    emoca:
      state_dict: ./third_party/EMOCABasic/data/emoca_basic.ckpt
    dan:
      state_dict: ./third_party/DAN/checkpoints/affecnet7_epoch6_acc0.6569.pth
      norm: ./third_party/DAN/dan_norm.pt
    wav2vec2:
      pretrained: ./third_party/wav2vec2/pretrained_model
      cache: ./third_party/wav2vec2/cache
    faceformer:
      template: ./third_party/FaceFormer/vocaset/template_pkl
      state_dict: ./third_party/FaceFormer/vocaset/vocaset.pth
      wav2vec2: ./third_party/FaceFormer/facebook/wav2vec2-base-960h

seed: 1000
device: "cuda:0"
preload_device: "cuda:1"



    

  