---
model_name: fusion_origin

load_from_checkpoint: false
debug: 0
fps: 30

flexible_loader:
  train_batchsize: 128 # the batch size for weight update and scheduler update
  train_minibatch: 64 # batch size for loss backward, smaller minibatch will avoid memory running out, but take longer to train
  valid_batchsize: 16 # if batch size for valid dataset > 1, best / worst samples can not be located exactly. 
  test_batchsize: 1

grad_check:
  enable: true
  peroid_epoch: 5


